gns3_server: "localhost"
gns3_port: "3080"

project_name: "untitled"

nodes:
  - appliance_name: "EthernetSwitch"
    node_name: EthSwitch1
    x: 0
    y: 0
  - appliance_name: "NAT"
    node_name: Nat1
    x: 0
    y: 250
  - appliance_name: "TestNode"
    node_name: TestNode1
    instances:
    x: 50
    y: -170
    ip: "192.168.122.10 255.255.255.0"
    gw: "192.168.122.1"

links:
  - node1: EthSwitch1
    port_num1: 0
    node2: Nat1
    port_num2: 0
  - node1: EthSwitch1
    port_num1: 1
    node2: TestNode1
    port_num2: 0

#  - EthSwitch1--Nat1
#  - EthSwtich1--TestNode1
